### ISSUE TITLE
Throw unexisting pokeball

### ISSUE THREAD

**Issue by Metropy** [disdain13/PokeRoadie#71]
I noticed the following behavior:
The bot tries to throw pokeballs, even if they do not exist in the inventory, causing a catch error:

Log:
`[20:12:31] ====== Items (352) ======`
`[20:12:31] RazzBerry x 4`
`[20:12:31] PokeBall x 42`
`[20:12:31] GreatBall x 2`
`[20:12:31] UltraBall x 0`
`...`
`[20:12:33] Found 93 Pokestops`
`[20:12:33] (INFO) Found 4 with lure!`
`[20:12:34] Santa Monica Pier Art WITH LURE in 50,31 m distance`
`[20:12:34] Distance to target location: 50,31 meters. Will take 18,11 seconds jogging at 10kmh`
`[20:12:39] Found 4 catchable Pokemon`
`[20:12:47] (Wild Success) | Spearow (...) | Chance: 0,53 | with a PokeBall and received XP 210`
`[20:12:59] (Wild Success) | Zubat (...) | Chance: 0,43 | with a GreatBall and received XP 210`
`[20:13:05] (Wild Error) | Onix (...) | Chance: 0,21 | with a UltraBall`
`[20:13:15] (Wild Error) | Pidgeotto (...) | Chance: 0,21 | with a UltraBall`

This does not depend on PokeBallBalancing or EnableHumanizedThrows.
Turning them off does not erase the problem.

I assume, ForceExcellentThrowOver and ForceGreatThrowOver do ignore the inventory.

**Comment by disdain13** [comment]
I will look into it for the next release.

**Comment by disdain13** [comment]
OK, this is fixed in the next release.

**Comment by Metropy** [comment]
Thanks for the fast fix and the new release.
However, the issue remains...

`[23:13:41] ====== Items (345) ======`
`[23:13:41] PokeBall x 40`
`[23:13:41] GreatBall x 0`
`[23:13:41] UltraBall x 0`
`...`
`[23:13:59] Found 4 catchable Pokemon`
`[23:14:00] (THROW) Excellent Ultra ball curve toss...`
`[23:14:00] ItemRazzBerry used, remaining: 0`
`[23:14:04] (Wild Error) | Ponyta (...) | Chance: 0,29 | with a UltraBall`
`[23:14:16] (THROW) Nice Ultra ball curve toss...`
`[23:14:16] (Wild Error) | NidoranFemale (...) | Chance: 0,37 | with a UltraBall`

I used the default config settings. version 2016.8.20.2
The bot throws a UltraBall, even if there are clearly no UltraBalls in the inventory, resulting in a 'Wild Error'.
